#!/bin/bash -e

source ~/.bashrc

# Kobus: use local cache if available
if [ -d "/work/share" ]; then
	export DL_DIR="/work/share/downloads"
    export SSTATE_DIR="/work/share/sstate-cache"
    # export PERSISTENT_DIR="/work/share/yocto_persistent"
    export BB_ENV_PASSTHROUGH_ADDITIONS="DL_DIR SSTATE_DIR"
fi

KAS_WORK_DIR=`pwd`
# workdir from input if entered else use current
if [ "$1" ]; then 
    KAS_WORK_DIR="$1"
    KASFILE="$1.yaml"
fi 

ubuntu=$(grep -q '22.04' /etc/os-release && echo yes)
export KAS_WORK_DIR

kas checkout "$KASFILE"

if [ "$ubuntu" ];  then
    source "$KAS_WORK_DIR/poky/oe-init-build-env" "$KAS_WORK_DIR/build"
else
    kas checkout "$KASFILE"
    kas shell
fi
