SUMMARY = "Ka-Ro bootfs Image"
LICENSE = "MIT"

require karo-subimage.inc

IMAGE_FSTYPES = "ext4 tar.bz2"

IMAGE_PARTITION_MOUNTPOINT = "/boot"
IMAGE_PARTITION_MOUNTPOINT_stm32mp1 = "${STM32MP_BOOTFS_MOUNTPOINT_IMAGE}"
IMAGE_NAME_SUFFIX = ".bootfs"

IMAGE_ROOTFS_SIZE ?= "32768"
IMAGE_ROOTFS_SIZE_stm32mp1 = "${BOOTFS_PARTITION_SIZE}"
IMAGE_ROOTFS_MAXSIZE_stm31mp1 = "${BOOTFS_PARTITION_SIZE}"

IMAGE_INSTALL_append = " karo-devicetrees kernel-image"
