SUMMARY = "Ka-Ro userfs Image"
LICENSE = "MIT"

require karo-subimage.inc

IMAGE_FSTYPES = "ext4 tar.bz2"

IMAGE_NAME_SUFFIX = ".userfs"

IMAGE_PARTITION_MOUNTPOINT = "/usr/local"
IMAGE_PARTITION_MOUNTPOINT_stm32mp1 = "${STM32MP_USERFS_MOUNTPOINT_IMAGE}"

IMAGE_ROOTFS_MAXSIZE_stm32mp1 = "${USERFS_PARTITION_SIZE}"
IMAGE_ROOTFS_SIZE_stm32mp1 = "${USERFS_PARTITION_SIZE}"
