# ---------------------------------------------------------------------------
# CI workflows for scailx based on pure kas workflow
# ---------------------------------------------------------------------------
#
# This software is a part of Scailx
# Copyright (C) 2023 Videology Inc
#
# ---------------------------------------------------------------------------
# SPDX-License-Identifier: MIT
# ---------------------------------------------------------------------------

name: kas build

on:
  push:

env:
  RELEASE: nanbield
  PACKAGE_FEED_GPG_PASSPHRASE_FILE: /tmp/pkgfeed_password_file
  BB_GENERATE_MIRROR_TARBALLS: 0
  BB_ENV_PASSTHROUGH_ADDITIONS: BB_GENERATE_MIRROR_TARBALLS PACKAGE_FEED_GPG_PASSPHRASE_FILE BB_HASHSERVE_UPSTREAM SSTATE_MIRRORS

jobs:
  kas-ci:
    name: Build kas/ci targets
    runs-on: ubuntu-jammy-16c
    # runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Free Disk Space
      #   uses: ./.github/workflows/free-disk-space
      - id: scailx_version
        run: |
          SCAILX_VERSION=$(grep 'SCAILX_VERSION' scailx_$RELEASE.yaml | cut -d '=' -f2 | xargs)
          echo "OUT=$SCAILX_VERSION" >> $GITHUB_OUTPUT
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.PKGFEED_GPG_PRIVATEKEY }}
          passphrase: ${{ secrets.PKGFEED_GPG_PASSWORD }}
      - run:
          mkdir -p `dirname "$PACKAGE_FEED_GPG_PASSPHRASE_FILE"` && echo "${{ secrets.PKGFEED_GPG_PASSWORD }}" > $PACKAGE_FEED_GPG_PASSPHRASE_FILE
      - name: import ssh key for private repos
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.DEPLOY_KEY }}'
          ssh-add - <<< '${{ secrets.DEPLOY_KEY2 }}'
      - name: install yocto dependencies
        run: |
          sudo apt-get update && export DEBIAN_FRONTEND=noninteractive && sudo apt-get -y install gawk wget git git-lfs diffstat unzip texinfo gcc build-essential chrpath socat cpio python3-pexpect xz-utils debianutils \
          iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint xterm python3-subunit mesa-common-dev zstd liblz4-tool file fuse3 mergerfs
          sudo pip3 install --no-input kas
          sudo rm /bin/sh && sudo ln -s bash /bin/sh
      - name: Setup Rclone
        env:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
        run: |
          mkdir -p ~/.config/rclone
          curl https://rclone.org/install.sh | bash
          echo "$rclone_config" | base64 -d > ~/.config/rclone/rclone.conf
          rclone version
      - name: mount cache dir
        uses: ./.github/workflows/bucket-mount
        with:
          MOUNT_PATH: ${{ github.workspace }}/build/bucket-cache
          BUCKET_PATH: scailx-storage:scailx-jammy/${{ env.RELEASE }}/sstate-cache
      # - name: sync sstate
      #   run: |
      #     mkdir -p ./build/sstate-cache
      #     rclone sync scailx-storage:scailx-jammy/$RELEASE/sstate-cache ./build/sstate-cache --transfers 64
      - name: Build yocto
        env:
            KAS_ALLOW_ROOT: yes
        run: |
          set -x
          if [ -f ${{ github.workspace }}/build/bucket-cache/cache/hashserv.db ]; then
            kas shell -c "bitbake-hashserv --read-only --bind :8987 --database ${{ github.workspace }}/build/bucket-cache/cache/hashserv.db &"
            sleep 5
            if lsof -i:8987; then
              export BB_HASHSERVE_UPSTREAM="localhost:8987"
              export SSTATE_MIRRORS="file://.* file://${{ github.workspace }}/build/bucket-cache/sstate-cache/PATH"
            fi
          fi
          kas build --target linux-imx                "scailx_$RELEASE.yaml"    || echo "yocto build failed"
          # kas build --target scailx-image-swuodate-ml "scailx_$RELEASE.yaml"    || echo "yocto build failed"
          # kas build --target scailx-bootstrap-image   "scailx_$RELEASE.yaml"    || echo "yocto build failed"
          # kas build --target package-index            "scailx_$RELEASE.yaml"    || echo "yocto build failed"
